ASSISTANT_DEBOUNCE_SECONDS = 2.0
CHAT_DEBOUNCE_MIN_SECONDS = 5.0
CHAT_DEBOUNCE_MAX_SECONDS = 15.0
CHAT_TEXT_COOLDOWN_SECONDS = 15 * 60
CHAT_REACTION_COOLDOWN_SECONDS = 2 * 60
CONVERSATION_INACTIVITY_SECONDS = 12 * 60 * 60
DEFAULT_CONVERSATION_RESET_MINUTES = CONVERSATION_INACTIVITY_SECONDS // 60
ATTACHMENT_CONTEXT_MAX_CHARACTERS = 100
EMBED_IMAGE_MAX_COUNT = 4
MEMORY_DOCUMENT_MESSAGE_TRIGGER = 50
MEMORY_DOCUMENT_TOKEN_TRIGGER = 4000
MEMORY_DOCUMENT_NEW_CONTEXT_TOKENS = 4000
MEMORY_DOCUMENT_TOTAL_CONTEXT_TOKENS = 5000
MEMORY_DOCUMENT_ATTACHMENT_WAIT_SECONDS = 60
MEMORY_DOCUMENT_PERSON_TARGET_CHARACTERS = 800
MEMORY_DOCUMENT_PERSON_MAX_CHARACTERS = 1000
MEMORY_DOCUMENT_SHARED_TARGET_CHARACTERS = 1200
MEMORY_DOCUMENT_SHARED_MAX_CHARACTERS = 1500
HISTORY_SYNC_INITIAL_LOOKBACK_HOURS = 12
HISTORY_SYNC_MAXIMUM_LOOKBACK_DAYS = 30
DISCORD_RESPONSE_CHUNK_LENGTH = 1900

MEMBER_ALIAS_SHEET_NAME = "別名管理"
MEMBER_ALIAS_MEMBER_SHEET_NAME = "メンバー一覧"
MEMBER_ALIAS_ACTION_LABELS = {
    "keep": "変更なし",
    "change_target": "対象者を変更",
    "invalidate": "無効化",
}
MEMBER_ALIAS_STATUS_LABELS = {
    "active": "有効",
    "ambiguous": "曖昧",
    "invalidated": "無効",
}
MEMBER_ALIAS_HEADERS = (
    "処理",
    "別名",
    "変更後の対象者",
    "現在の対象者",
    "状態",
    "根拠",
    "投稿リンク",
    "更新日時",
    "別名ID",
    "対象者ID",
    "正規化別名",
)
MEMBER_ALIAS_EVIDENCE_COLUMN = 6
