name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  actionlint:
    permissions:
      checks: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
          fail_level: any

  hadolint:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.5.0
        with:
          dockerfile: Dockerfile

  lint:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            papyrus
            papyrus-prompt

      - uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          submodules: recursive

      - uses: astral-sh/setup-uv@v10.0.1

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Run ruff check
        run: uv run ruff check .

      - name: Run ruff format check
        run: uv run ruff format --check .

      - name: Run ty check
        run: uv run ty check .
